import type { Theme } from "../types/theme"

export const catppuccinMocha: Theme = {
   id: "catppuccin-mocha",
   name: "Catppuccin Mocha",
   colors: {
      background: "#1e1e2e",
      surface: "#181825",
      surface2: "#252536",
      sidebar: "#14141f",
      sidebarActive: "#cba6f7",
      sidebarHover: "#2a2a3d",
      border: "#313244",
      text: "#cdd6f4",
      textMuted: "#6c7086",
      primary: "#cba6f7",
      secondary: "#bac2de",
      success: "#a6e3a1",
      warning: "#f9e2af",
      error: "#f38ba8",
      accent: "#cba6f7",
      editorBackground: "#1e1e2e",
      editorSelection: "#33415e",
      editorCursor: "#f5e0dc",
      resultGrid: "#181825",
      resultGridBorder: "#313244",
      tabBackground: "#14141f",
      tabActive: "#1e1e2e",
      statusBar: "#14141f",
      queryAccent: "#94e2d5",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "cba6f7", fontStyle: "bold" },
         { token: "predefined", foreground: "89dceb" },
         { token: "identifier", foreground: "cdd6f4" },
         { token: "string", foreground: "a6e3a1" },
         { token: "number", foreground: "fab387" },
         { token: "comment", foreground: "6c7086", fontStyle: "italic" },
         { token: "operator", foreground: "89dceb" },
         { token: "delimiter", foreground: "bac2de" },
         { token: "type", foreground: "94e2d5" },
      ],
      colors: {
         "editor.background": "#1e1e2e",
         "editor.foreground": "#cdd6f4",
         "editorLineNumber.foreground": "#33415e",
         "editorLineNumber.activeForeground": "#7f849c",
         "editor.selectionBackground": "#33415e",
         "editor.inactiveSelectionBackground": "#33415e80",
         "editorCursor.foreground": "#f5e0dc",
         "editorIndentGuide.background": "#252536",
         "editorIndentGuide.activeBackground": "#45475a",
         "editor.lineHighlightBackground": "#252536",
         "editorWidget.background": "#181825",
         "editorWidget.border": "#313244",
         "editorBracketMatch.background": "#2a2a3d",
         "editorBracketMatch.border": "#cba6f7",
         "scrollbarSlider.background": "#31324480",
         "scrollbarSlider.hoverBackground": "#313244",
         "scrollbarSlider.activeBackground": "#45475a",
      },
   },
}
