import type { Theme } from "~/types/theme"

export const defaultTheme: Theme = {
   id: "default",
   name: "Default",
   colors: {
      background: "#0a0a0a",
      surface: "#121212",
      surface2: "#1a1a1a",
      sidebar: "#101010",
      sidebarActive: "#2d7d6f",
      sidebarHover: "#242424",
      border: "#1e1e1e",
      text: "#e8e8e8",
      textMuted: "#5a5a5a",
      primary: "#2d7d6f",
      secondary: "#888888",
      success: "#2d7d6f",
      warning: "#c28938",
      error: "#c94a4a",
      accent: "#2d7d6f",
      editorBackground: "#101414",
      editorSelection: "#2f3d5e",
      editorCursor: "#c0caf5",
      resultGrid: "#0D0D0D",
      resultGridBorder: "#1e1e1e",
      tabBackground: "#0D0D0D",
      tabActive: "#2d7d6f",
      statusBar: "#0a0a0a",
      queryAccent: "#bb9af7",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "2d7d6f", fontStyle: "bold" },
         { token: "predefined", foreground: "4db89e" },
         { token: "predefined.sql", foreground: "4db89e" },
         { token: "identifier", foreground: "e8e8e8" },
         { token: "string", foreground: "2d7d6f" },
         { token: "string.sql", foreground: "2d7d6f" },
         { token: "number", foreground: "c28938" },
         { token: "comment", foreground: "5a5a5a", fontStyle: "italic" },
         { token: "operator", foreground: "888888" },
         { token: "operator.sql", foreground: "888888" },
         { token: "delimiter", foreground: "888888" },
         { token: "type", foreground: "bb9af7" },
      ],
      colors: {
         "editor.background": "#0D0D0D",
         "editor.foreground": "#e8e8e8",
         "editorLineNumber.foreground": "#1a1a1a",
         "editorLineNumber.activeForeground": "#2d7d6f",
         "editor.lineHighlightBackground": "#101010",
         "editor.selectionBackground": "#2f3d5e",
         "editor.inactiveSelectionBackground": "#2f3d5e80",
         "editorCursor.foreground": "#c0caf5",
         "editorIndentGuide.background": "#121212",
         "editorIndentGuide.activeBackground": "#242424",
         "editorWidget.background": "#121212",
         "editorWidget.border": "#1e1e1e",
         "editorBracketMatch.background": "#1a1a1a",
         "editorBracketMatch.border": "#2d7d6f",
         "scrollbarSlider.background": "#1e1e1e80",
         "scrollbarSlider.hoverBackground": "#1e1e1e",
         "scrollbarSlider.activeBackground": "#2d2d2d",
      },
   },
}
