import type { Theme } from "../types/theme"

export const dracula: Theme = {
   id: "dracula",
   name: "Dracula",
   colors: {
      background: "#282a36",
      surface: "#21222c",
      surface2: "#2f3141",
      sidebar: "#1c1d26",
      sidebarActive: "#bd93f9",
      sidebarHover: "#383a4a",
      border: "#3f4151",
      text: "#f8f8f2",
      textMuted: "#6272a4",
      primary: "#bd93f9",
      secondary: "#e0e0e0",
      success: "#50fa7b",
      warning: "#f1fa8c",
      error: "#ff5555",
      accent: "#bd93f9",
      editorBackground: "#282a36",
      editorSelection: "#3f3f5a",
      editorCursor: "#f8f8f2",
      resultGrid: "#21222c",
      resultGridBorder: "#3f4151",
      tabBackground: "#1c1d26",
      tabActive: "#282a36",
      statusBar: "#1c1d26",
      queryAccent: "#8be9fd",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "bd93f9", fontStyle: "bold" },
         { token: "identifier", foreground: "f8f8f2" },
         { token: "string", foreground: "f1fa8c" },
         { token: "number", foreground: "ffb86c" },
         { token: "comment", foreground: "6272a4", fontStyle: "italic" },
         { token: "operator", foreground: "ff79c6" },
         { token: "delimiter", foreground: "f8f8f2" },
         { token: "type", foreground: "8be9fd" },
      ],
      colors: {
         "editor.background": "#282a36",
         "editor.foreground": "#f8f8f2",
         "editorLineNumber.foreground": "#3f4151",
         "editorLineNumber.activeForeground": "#6272a4",
         "editor.selectionBackground": "#3f3f5a",
         "editor.inactiveSelectionBackground": "#3f3f5a80",
         "editorCursor.foreground": "#f8f8f2",
         "editorIndentGuide.background": "#2f3141",
         "editorIndentGuide.activeBackground": "#4a4d5e",
         "editor.lineHighlightBackground": "#2f3141",
         "editorWidget.background": "#21222c",
         "editorWidget.border": "#3f4151",
         "editorBracketMatch.background": "#3f3f5a",
         "editorBracketMatch.border": "#bd93f9",
      },
   },
}
