import type { Theme } from "../types/theme"

export const githubDark: Theme = {
   id: "github-dark",
   name: "GitHub Dark",
   colors: {
      background: "#0d1117",
      surface: "#161b22",
      surface2: "#21262d",
      sidebar: "#0d1117",
      sidebarActive: "#58a6ff",
      sidebarHover: "#1c2128",
      border: "#30363d",
      text: "#e6edf3",
      textMuted: "#8b949e",
      primary: "#58a6ff",
      secondary: "#8b949e",
      success: "#3fb950",
      warning: "#d29922",
      error: "#f85149",
      accent: "#58a6ff",
      editorBackground: "#0d1117",
      editorSelection: "#1f3a5f",
      editorCursor: "#e6edf3",
      resultGrid: "#0d1117",
      resultGridBorder: "#30363d",
      tabBackground: "#0d1117",
      tabActive: "#0d1117",
      statusBar: "#0d1117",
      queryAccent: "#d2a8ff",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "ff7b72", fontStyle: "bold" },
         { token: "identifier", foreground: "e6edf3" },
         { token: "string", foreground: "a5d6ff" },
         { token: "number", foreground: "79c0ff" },
         { token: "comment", foreground: "8b949e", fontStyle: "italic" },
         { token: "operator", foreground: "79c0ff" },
         { token: "delimiter", foreground: "e6edf3" },
         { token: "type", foreground: "ffa657" },
      ],
      colors: {
         "editor.background": "#0d1117",
         "editor.foreground": "#e6edf3",
         "editorLineNumber.foreground": "#30363d",
         "editorLineNumber.activeForeground": "#6e7681",
         "editor.selectionBackground": "#1f3a5f",
         "editor.inactiveSelectionBackground": "#1f3a5f80",
         "editorCursor.foreground": "#e6edf3",
         "editorIndentGuide.background": "#21262d",
         "editorIndentGuide.activeBackground": "#30363d",
         "editor.lineHighlightBackground": "#161b22",
         "editorWidget.background": "#161b22",
         "editorWidget.border": "#30363d",
         "editorBracketMatch.background": "#1f3a5f",
         "editorBracketMatch.border": "#58a6ff",
      },
   },
}
