import type { Theme } from "~/types/theme"

export const gruvboxDark: Theme = {
   id: "gruvbox-dark",
   name: "Gruvbox Dark",
   colors: {
      background: "#282828",
      surface: "#1d2021",
      surface2: "#32302f",
      sidebar: "#181919",
      sidebarActive: "#d79921",
      sidebarHover: "#3c3836",
      border: "#504945",
      text: "#ebdbb2",
      textMuted: "#7c6f64",
      primary: "#d79921",
      secondary: "#d5c4a1",
      success: "#98971a",
      warning: "#d79921",
      error: "#cc241d",
      accent: "#d79921",
      editorBackground: "#282828",
      editorSelection: "#3d352e",
      editorCursor: "#ebdbb2",
      resultGrid: "#1d2021",
      resultGridBorder: "#504945",
      tabBackground: "#181919",
      tabActive: "#282828",
      statusBar: "#181919",
      queryAccent: "#8ec07c",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "fb4934", fontStyle: "bold" },
         { token: "predefined", foreground: "8ec07c" },
         { token: "predefined.sql", foreground: "8ec07c" },
         { token: "identifier", foreground: "ebdbb2" },
         { token: "string", foreground: "98971a" },
         { token: "string.sql", foreground: "98971a" },
         { token: "number", foreground: "d79921" },
         { token: "comment", foreground: "7c6f64", fontStyle: "italic" },
         { token: "operator", foreground: "fe8019" },
         { token: "operator.sql", foreground: "fe8019" },
         { token: "delimiter", foreground: "d5c4a1" },
         { token: "type", foreground: "8ec07c" },
      ],
      colors: {
         "editor.background": "#282828",
         "editor.foreground": "#ebdbb2",
         "editorLineNumber.foreground": "#504945",
         "editorLineNumber.activeForeground": "#7c6f64",
         "editor.selectionBackground": "#3d352e",
         "editor.inactiveSelectionBackground": "#3d352e80",
         "editorCursor.foreground": "#ebdbb2",
         "editorIndentGuide.background": "#32302f",
         "editorIndentGuide.activeBackground": "#504945",
         "editor.lineHighlightBackground": "#32302f",
         "editorWidget.background": "#1d2021",
         "editorWidget.border": "#504945",
         "editorBracketMatch.background": "#3d352e",
         "editorBracketMatch.border": "#d79921",
         "scrollbarSlider.background": "#50494580",
         "scrollbarSlider.hoverBackground": "#504945",
         "scrollbarSlider.activeBackground": "#665c54",
      },
   },
}
