import type { Theme } from "../types/theme"

export const kanagawa: Theme = {
   id: "kanagawa",
   name: "Kanagawa",
   colors: {
      background: "#1f1f2e",
      surface: "#1a1a28",
      surface2: "#2a2a3d",
      sidebar: "#151521",
      sidebarActive: "#7fb4ca",
      sidebarHover: "#2e2e42",
      border: "#36354a",
      text: "#dcd7ba",
      textMuted: "#6a6a7e",
      primary: "#7fb4ca",
      secondary: "#c8c3a0",
      success: "#76946a",
      warning: "#c0a36e",
      error: "#c34043",
      accent: "#7fb4ca",
      editorBackground: "#1f1f2e",
      editorSelection: "#2e2e42",
      editorCursor: "#dcd7ba",
      resultGrid: "#1a1a28",
      resultGridBorder: "#36354a",
      tabBackground: "#151521",
      tabActive: "#1f1f2e",
      statusBar: "#151521",
      queryAccent: "#e6c384",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "7e9cd8", fontStyle: "bold" },
         { token: "identifier", foreground: "dcd7ba" },
         { token: "string", foreground: "76946a" },
         { token: "number", foreground: "e6c384" },
         { token: "comment", foreground: "6a6a7e", fontStyle: "italic" },
         { token: "operator", foreground: "7fb4ca" },
         { token: "delimiter", foreground: "c8c3a0" },
         { token: "type", foreground: "98bb6c" },
      ],
      colors: {
         "editor.background": "#1f1f2e",
         "editor.foreground": "#dcd7ba",
         "editorLineNumber.foreground": "#36354a",
         "editorLineNumber.activeForeground": "#6a6a7e",
         "editor.selectionBackground": "#2e2e42",
         "editor.inactiveSelectionBackground": "#2e2e4280",
         "editorCursor.foreground": "#dcd7ba",
         "editorIndentGuide.background": "#2a2a3d",
         "editorIndentGuide.activeBackground": "#36354a",
         "editor.lineHighlightBackground": "#2a2a3d",
         "editorWidget.background": "#1a1a28",
         "editorWidget.border": "#36354a",
         "editorBracketMatch.background": "#2e2e42",
         "editorBracketMatch.border": "#7fb4ca",
      },
   },
}
