import type { Theme } from "~/types/theme"

export const nord: Theme = {
   id: "nord",
   name: "Nord",
   colors: {
      background: "#2e3440",
      surface: "#272c37",
      surface2: "#3b4252",
      sidebar: "#232831",
      sidebarActive: "#88c0d0",
      sidebarHover: "#434c5e",
      border: "#4c566a",
      text: "#eceff4",
      textMuted: "#616e88",
      primary: "#88c0d0",
      secondary: "#d8dee9",
      success: "#a3be8c",
      warning: "#ebcb8b",
      error: "#bf616a",
      accent: "#88c0d0",
      editorBackground: "#2e3440",
      editorSelection: "#3b4252",
      editorCursor: "#eceff4",
      resultGrid: "#272c37",
      resultGridBorder: "#4c566a",
      tabBackground: "#232831",
      tabActive: "#2e3440",
      statusBar: "#232831",
      queryAccent: "#b48ead",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "81a1c1", fontStyle: "bold" },
         { token: "predefined", foreground: "88c0d0" },
         { token: "predefined.sql", foreground: "88c0d0" },
         { token: "identifier", foreground: "eceff4" },
         { token: "string", foreground: "a3be8c" },
         { token: "string.sql", foreground: "a3be8c" },
         { token: "number", foreground: "b48ead" },
         { token: "comment", foreground: "616e88", fontStyle: "italic" },
         { token: "operator", foreground: "88c0d0" },
         { token: "operator.sql", foreground: "88c0d0" },
         { token: "delimiter", foreground: "d8dee9" },
         { token: "type", foreground: "8fbcbb" },
      ],
      colors: {
         "editor.background": "#2e3440",
         "editor.foreground": "#eceff4",
         "editorLineNumber.foreground": "#4c566a",
         "editorLineNumber.activeForeground": "#81a1c1",
         "editor.selectionBackground": "#3b4252",
         "editor.inactiveSelectionBackground": "#3b425280",
         "editorCursor.foreground": "#eceff4",
         "editorIndentGuide.background": "#3b4252",
         "editorIndentGuide.activeBackground": "#4c566a",
         "editor.lineHighlightBackground": "#3b4252",
         "editorWidget.background": "#272c37",
         "editorWidget.border": "#4c566a",
         "editorBracketMatch.background": "#434c5e",
         "editorBracketMatch.border": "#88c0d0",
         "scrollbarSlider.background": "#4c566a80",
         "scrollbarSlider.hoverBackground": "#4c566a",
         "scrollbarSlider.activeBackground": "#616e88",
      },
   },
}
