import type { Theme } from "~/types/theme"

export const oneDark: Theme = {
   id: "one-dark",
   name: "One Dark",
   colors: {
      background: "#1e2127",
      surface: "#191c22",
      surface2: "#282c34",
      sidebar: "#16181d",
      sidebarActive: "#61afef",
      sidebarHover: "#2d3139",
      border: "#3a3f4a",
      text: "#abb2bf",
      textMuted: "#5c6370",
      primary: "#61afef",
      secondary: "#828997",
      success: "#98c379",
      warning: "#e5c07b",
      error: "#e06c75",
      accent: "#61afef",
      editorBackground: "#1e2127",
      editorSelection: "#2d3139",
      editorCursor: "#abb2bf",
      resultGrid: "#191c22",
      resultGridBorder: "#3a3f4a",
      tabBackground: "#16181d",
      tabActive: "#1e2127",
      statusBar: "#16181d",
      queryAccent: "#c678dd",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "c678dd", fontStyle: "bold" },
         { token: "predefined", foreground: "56b6c2" },
         { token: "predefined.sql", foreground: "56b6c2" },
         { token: "identifier", foreground: "abb2bf" },
         { token: "string", foreground: "98c379" },
         { token: "string.sql", foreground: "98c379" },
         { token: "number", foreground: "d19a66" },
         { token: "comment", foreground: "5c6370", fontStyle: "italic" },
         { token: "operator", foreground: "56b6c2" },
         { token: "operator.sql", foreground: "56b6c2" },
         { token: "delimiter", foreground: "abb2bf" },
         { token: "type", foreground: "61afef" },
      ],
      colors: {
         "editor.background": "#1e2127",
         "editor.foreground": "#abb2bf",
         "editorLineNumber.foreground": "#3a3f4a",
         "editorLineNumber.activeForeground": "#636d83",
         "editor.selectionBackground": "#2d3139",
         "editor.inactiveSelectionBackground": "#2d313980",
         "editorCursor.foreground": "#abb2bf",
         "editorIndentGuide.background": "#282c34",
         "editorIndentGuide.activeBackground": "#3a3f4a",
         "editor.lineHighlightBackground": "#282c34",
         "editorWidget.background": "#191c22",
         "editorWidget.border": "#3a3f4a",
         "editorBracketMatch.background": "#2d3139",
         "editorBracketMatch.border": "#61afef",
         "scrollbarSlider.background": "#3a3f4a80",
         "scrollbarSlider.hoverBackground": "#3a3f4a",
         "scrollbarSlider.activeBackground": "#4b5263",
      },
   },
}
