import type { Theme } from "~/types/theme"

export const rosePine: Theme = {
   id: "rose-pine",
   name: "Rose Pine",
   colors: {
      background: "#191724",
      surface: "#1f1d2e",
      surface2: "#26233a",
      sidebar: "#14121f",
      sidebarActive: "#c4a7e7",
      sidebarHover: "#2a2740",
      border: "#3b3557",
      text: "#e0def4",
      textMuted: "#6e6a86",
      primary: "#c4a7e7",
      secondary: "#908caa",
      success: "#31748f",
      warning: "#f6c177",
      error: "#eb6f92",
      accent: "#c4a7e7",
      editorBackground: "#191724",
      editorSelection: "#2a2740",
      editorCursor: "#e0def4",
      resultGrid: "#1f1d2e",
      resultGridBorder: "#3b3557",
      tabBackground: "#14121f",
      tabActive: "#191724",
      statusBar: "#14121f",
      queryAccent: "#9ccfd8",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "c4a7e7", fontStyle: "bold" },
         { token: "predefined", foreground: "9ccfd8" },
         { token: "predefined.sql", foreground: "9ccfd8" },
         { token: "identifier", foreground: "e0def4" },
         { token: "string", foreground: "31748f" },
         { token: "string.sql", foreground: "31748f" },
         { token: "number", foreground: "f6c177" },
         { token: "comment", foreground: "6e6a86", fontStyle: "italic" },
         { token: "operator", foreground: "9ccfd8" },
         { token: "operator.sql", foreground: "9ccfd8" },
         { token: "delimiter", foreground: "908caa" },
         { token: "type", foreground: "ebbcba" },
      ],
      colors: {
         "editor.background": "#191724",
         "editor.foreground": "#e0def4",
         "editorLineNumber.foreground": "#3b3557",
         "editorLineNumber.activeForeground": "#6e6a86",
         "editor.selectionBackground": "#2a2740",
         "editor.inactiveSelectionBackground": "#2a274080",
         "editorCursor.foreground": "#e0def4",
         "editorIndentGuide.background": "#26233a",
         "editorIndentGuide.activeBackground": "#3b3557",
         "editor.lineHighlightBackground": "#26233a",
         "editorWidget.background": "#1f1d2e",
         "editorWidget.border": "#3b3557",
         "editorBracketMatch.background": "#2a2740",
         "editorBracketMatch.border": "#c4a7e7",
         "scrollbarSlider.background": "#3b355780",
         "scrollbarSlider.hoverBackground": "#3b3557",
         "scrollbarSlider.activeBackground": "#524f67",
      },
   },
}
