import type { Theme } from "../types/theme"

export const tokyoNight: Theme = {
   id: "tokyo-night",
   name: "Tokyo Night",
   colors: {
      background: "#1a1b26",
      surface: "#16161e",
      surface2: "#1f2233",
      sidebar: "#13131d",
      sidebarActive: "#7dcfff",
      sidebarHover: "#252838",
      border: "#2f3346",
      text: "#c0caf5",
      textMuted: "#565f89",
      primary: "#7dcfff",
      secondary: "#a9b1d6",
      success: "#9ece6a",
      warning: "#e0af68",
      error: "#f7768e",
      accent: "#7dcfff",
      editorBackground: "#1a1b26",
      editorSelection: "#2f3d5e",
      editorCursor: "#c0caf5",
      resultGrid: "#14151f",
      resultGridBorder: "#2f3346",
      tabBackground: "#13131d",
      tabActive: "#1a1b26",
      statusBar: "#13131d",
      queryAccent: "#bb9af7",
   },
   monaco: {
      base: "vs-dark",
      rules: [
         { token: "keyword", foreground: "7dcfff", fontStyle: "bold" },
         { token: "identifier", foreground: "c0caf5" },
         { token: "string", foreground: "9ece6a" },
         { token: "number", foreground: "ff9e64" },
         { token: "comment", foreground: "565f89", fontStyle: "italic" },
         { token: "operator", foreground: "89ddff" },
         { token: "delimiter", foreground: "a9b1d6" },
         { token: "type", foreground: "bb9af7" },
      ],
      colors: {
         "editor.background": "#1a1b26",
         "editor.foreground": "#c0caf5",
         "editorLineNumber.foreground": "#2f3d5e",
         "editorLineNumber.activeForeground": "#737aa2",
         "editor.selectionBackground": "#2f3d5e",
         "editor.inactiveSelectionBackground": "#2f3d5e80",
         "editorCursor.foreground": "#c0caf5",
         "editorIndentGuide.background": "#1f2233",
         "editorIndentGuide.activeBackground": "#3d4470",
         "editor.lineHighlightBackground": "#1f2233",
         "editorWidget.background": "#16161e",
         "editorWidget.border": "#2f3346",
         "editorBracketMatch.background": "#1f2a45",
         "editorBracketMatch.border": "#7dcfff",
      },
   },
}
